first_msg = "Hi !\nPlease locate your file under folder named 'file_folder' in this directory, then input your file path\nNOTE !\n\tMimetype format '.txt'\n\tFile name example 'names_example.txt'\n\tFile path example 'file_folder//names_example'\n"
INPUT_FILE_WARNING = "WARNING !\nInput file path doesn't match with provided file's path"
ORDER_INPUT_STR = "Please choose an ordering to sort: 'Ascending' or 'Descending'\n"
CRITERIA_INPUT_STR = "Please choose criteria: 'Name', 'Surname' or 'PhoneNumberCode'\n"
EXIT_STR = "File is empty, exiting"
